site_name: Kitsu API Documentation
repo_url: https://github.com/cgwire/zou/
repo_name: Zou
edit_uri: edit/docs/docs
site_author: CGWire 
site_description: Documentation to install, configure and use the Kitsu API.
theme: readthedocs
